#!/bin/bash
# shellcheck disable=SC2046

set -e

source $RY_ROOT/utils/util

if ! command -v session-manager-plugin &> /dev/null
then
    info "Install session manager plugin"
    if [ "$(uname)" == "Darwin" ]; then
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/mac/sessionmanager-bundle.zip" -o "sessionmanager-bundle.zip"
      unzip sessionmanager-bundle.zip
      sudo ./sessionmanager-bundle/install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin
      rm -rf sessionmanager-bundle/  sessionmanager-bundle.zip
    else
      info "Please install session manager plugin follow: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html"
    fi
fi

debug $RY_ECS_DIR_PATH

[ -d $RY_ECS_DIR_PATH ] && fatal "Rayyone ECS config dir existed!"

log_step "Creating config dir..."
mkdir -p $RY_ECS_DIR_PATH

log_step "Copying config files..."
cp $RY_ROOT/ecs/example.conf ./$RY_ECS_DIR_PATH/staging.conf
cp $RY_ROOT/ecs/.gitignore-example ./$RY_ECS_DIR_PATH/.gitignore
cp $RY_ROOT/ecs/GUIDE.template.md ./$RY_ECS_DIR_PATH/GUIDE.md

info "Success!"
info "Next steps:"
info "  1. Fill in '$RY_ECS_DIR_PATH/staging.conf' with your service details"
info "  2. Run 'ry ecs ecr-init -c=staging.conf' to create ECR repositories"
info "  3. Run 'ry ecs build -c=staging.conf' to push your first image"
info "  4. Deploy CloudFormation stack in aws-cf repo"
info ""
info "See '$RY_ECS_DIR_PATH/GUIDE.md' for full instructions."
